title: Robot Learning Collective
description: Robot learning, VLA models, embodied AI, and community projects.
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
markdown: kramdown
github:
  is_project_page: false
